### ISSUE TITLE
Better documentation for the templates

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#232]
### Generic Issue

* xscen version: 0.6.15

### Description
I've been helping @vindelico get accustomed to `xscen` in the last few weeks, and he had a few suggestions for our templates (especially the first 1, which is the most complete one).

1. Be as exhaustive as possible.
In some places in the config, we only write the arguments that are being overwritten. The reason why some arguments are missing wasn't clear. Something like this would be preferable:
```
  climatological_mean: # automatically passed to the function
    window: 30
    min_periods:  # Default value, so you would not need to include it in a real configuration file.
    interval: 10
    periods: [['1951', '2100']]
    to_level: climatology
```

2. Better explain why certain functions (i.e. `compute_deltas`) are under specific categories (i.e `aggregate`)
```
# Functions under this section are associated to xscen/aggregate.py
aggregate:
  dask:
    n_workers: 4
    threads_per_worker: 4
    memory_limit: "6GB"
  ...
```

3. Better order/indicate which function gets sent automatically to `xscen` through `parse_config` and which doesn't.
```
aggregate:
  # These entries do not correspond to an `xscen` function, but if you plan to have multiple variations of them
  # (i.e. to fine-tune dask workers depending on the task to perform), then categorizing them under `aggregate` 
  # makes it easier to locate them within the CONFIG object when you want to perform tasks related to the
  # `aggregate` module, such as when computing `climatological_mean`
  dask:
    n_workers: 4
    threads_per_worker: 4
    memory_limit: "6GB"
  input:
    clim:
      processing_level: indicators
    delta:
      processing_level: climatology
  save:
    mode: 'o'

  # These entries exactly match `xscen` functions located under the `aggregate` module, so the parameters 
  # specified below will automatically override default values. 
  # See https://xscen.readthedocs.io/en/latest/notebooks/6_config.html for more details on how it works.
  climatological_mean: 
    window: 30
    interval: 10
    periods: [['1951', '2100']]
    to_level: climatology
  compute_deltas: 
    kind: "+"
    reference_horizon: "1991-2020"
    to_level: 'delta'

```
