### ISSUE TITLE
Supprimer @parse_config

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xscen#612]
### Generic Issue

Proposition radicale peut-être. Je propose de retirer cette manière de donner de la config à xscen. Ainsi, dans le yaml de config une construction du genre:
```yaml
[module]:
    [fonction]:
        [argument]: valeur
```
ne sera plus possible.

Mon expérience personnelle récente c'est que cette manière de configurer xscen n'est pas intuitive du tout. À part peut-être pour les celleux qui travaillent sur xscen depuis `scenarios_main`, toutes les personnes à qui j'ai expliqué le concept m'ont regardé avec la face  😵‍💫.  Et je les comprends très bien, c'était cool à implémenter, mais c'est mêlant pas mal.

Dans les configs d'ESPO, par exemple, on mélange ça avec des options "customs" qui sont passées explicitement via le workflow. Je propose qu'on ne fasse que ça.

Je laisserais les sections "automatiques" : `xclim`, `xarray`, `logging`,  `dask`. Mais pour le reste, si une option apparait dans la config yaml, il faut qu'elle apparaisse comme `CONFIG['section']['clef']` quelque part dans le script, plus de magie noire.

**Comment by aulemahal** [comment]
Exemple avec une section modifiée de la config d'ESPO:

```yaml
regrid:
  target:
    source: *ref_source
    calendar: noleap
  regrid_dataset:
      regridder_kwargs:
        method: bilinear
        extrap_method: inverse_dist
        locstream_out: *stack
        reuse_weights: False
        output_chunks:
          loc: -1
```

La sous-section "target" est **custom** alors que la `regrid_dataset` est automatisée, i.e dans le script on voit : 
```python3
ds_target = pcat.search(**CONFIG['regrid']['target'], domain=region_name).to_dask()

ds_regrid = regrid_dataset(
    ds=ds_input,
    ds_grid=ds_target,
)
```

Avec ma proposition, on devra écrire:
```python3
ds_target = pcat.search(**CONFIG['regrid']['target'], domain=region_name).to_dask()

ds_regrid = regrid_dataset(
    ds=ds_input,
    ds_grid=ds_target,
    **CONFIG['regrid']['regrid_dataset']
)
```
